version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sample"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17nqo9sbbafd8"
s3_prefix = "sample"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
